# Generated by Django 5.0.4 on 2024-04-26 03:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tayangan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=100)),
                ('sinopsis', models.CharField(max_length=255)),
                ('asal_negara', models.CharField(max_length=50)),
                ('sinopsis_trailer', models.CharField(max_length=255)),
                ('url_video_trailer', models.CharField(max_length=255)),
                ('release_date_trailer', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sutradara',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('tayangan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infolist.tayangan')),
                ('url_video_film', models.CharField(max_length=255)),
                ('release_date_film', models.DateField()),
                ('durasi_film', models.IntegerField()),
            ],
            bases=('infolist.tayangan',),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('tayangan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infolist.tayangan')),
            ],
            bases=('infolist.tayangan',),
        ),
        migrations.AddField(
            model_name='tayangan',
            name='sutradara',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infolist.sutradara'),
        ),
    ]
