# Generated by Django 5.0.4 on 2024-05-06 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pemain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(default='Anonim', max_length=50)),
                ('jenis_kelamin', models.IntegerField(choices=[(0, 'Laki-laki'), (1, 'Perempuan')], default=0)),
                ('kewarganegaraan', models.CharField(default='Indonesia', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Penulis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(default='Anonim', max_length=50)),
                ('jenis_kelamin', models.IntegerField(choices=[(0, 'Laki-laki'), (1, 'Perempuan')], default=0)),
                ('kewarganegaraan', models.CharField(default='Indonesia', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sutradara',
            name='jenis_kelamin',
            field=models.IntegerField(choices=[(0, 'Laki-laki'), (1, 'Perempuan')], default=0),
        ),
        migrations.AddField(
            model_name='sutradara',
            name='kewarganegaraan',
            field=models.CharField(default='Indonesia', max_length=50),
        ),
        migrations.AddField(
            model_name='sutradara',
            name='nama',
            field=models.CharField(default='Anonim', max_length=50),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_judul', models.CharField(max_length=100)),
                ('sinopsis', models.CharField(max_length=255)),
                ('durasi', models.IntegerField(default=0)),
                ('url_video', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('id_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infolist.series')),
            ],
            options={
                'unique_together': {('id_series', 'sub_judul')},
            },
        ),
    ]
