# Generated by Django 5.0.4 on 2024-05-06 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('tipe', models.CharField(max_length=50)),
                ('jenis_kelamin', models.IntegerField()),
                ('kewarganegaraan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pemain',
            fields=[
                ('contributors_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contributors.contributors')),
            ],
            bases=('contributors.contributors',),
        ),
        migrations.CreateModel(
            name='PenulisSkenario',
            fields=[
                ('contributors_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contributors.contributors')),
            ],
            bases=('contributors.contributors',),
        ),
        migrations.CreateModel(
            name='Sutradara',
            fields=[
                ('contributors_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contributors.contributors')),
            ],
            bases=('contributors.contributors',),
        ),
    ]
