# Generated by Django 5.0.4 on 2024-04-26 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('nama', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('harga', models.PositiveIntegerField()),
                ('resolusi_layar', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('id_tayangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infolist.tayangan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
