# Generated by Django 5.0.4 on 2024-04-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengguna',
            name='id_tayangan',
        ),
        migrations.AddField(
            model_name='pengguna',
            name='country',
            field=models.CharField(default='Indonesia', max_length=50),
            preserve_default=False,
        ),
    ]
