# Generated by Django 5.0.4 on 2024-05-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_pengguna_id_tayangan_pengguna_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pengguna',
        ),
    ]
